version: '3.8'

services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "./config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/docker/video:/opt/selenoid/video"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  app:
    build:
      context: .
    command: ["python", "main.py"]  # Atualize o caminho para o arquivo main.py
    volumes:
      - .:/app
    depends_on:
      - selenoid
